name: Release

on: 
  workflow_dispatch:

jobs:
  deploy-prod:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build
          path: output
          workflow: master.yml
          workflow_conclusion: success

      - name: Deploy
        run: ./scripts/deploy.sh